### ISSUE TITLE
License File missing

### ISSUE THREAD

**Issue by devenbansod** [zeke/lets-get-meta#2]
Hi @zeke, it would be great if you could add the LICENSE file with the correct copyright for ISC license (the ISC license is mentioned in the README).

It would make it simpler for other developers to use/extend your library in a proper way.

**Comment by zeke** [comment]
Thanks, @devenbansod. Pull requests welcome!

**Comment by devenbansod** [comment]
Hi @zeke I could do it, but I would surely prefer you add it with your correct copyright mentions. 

You can take a look [here](https://help.github.com/articles/adding-a-license-to-a-repository/) on how to simply add the LICENSE (or LICENSE.txt) file to the repository.

**Comment by zeke** [comment]
I change the license to MIT, add a `LICENSE` fiel and published a new major version to reflect the change of license.

```
❯ np major
 ✔ Prerequisite check
 ✔ Git
 ✔ Cleanup
 ✔ Installing dependencies
 ✔ Running tests
 ✔ Bumping version
 ✔ Publishing package
 ✔ Pushing tags

 lets-get-meta 2.0.0 published 🎉
```

**Comment by devenbansod** [comment]
Thanks a lot @zeke . I just made a PR at #3 to fix the LICENSE name in README too.
